package it.jobhunt.JobHunt.enums;

public enum JobRole {
    DEVELOPER, TESTER, ARCHITECT, ANALYST, ADMINISTRATOR, DEVOPS, SUPPORT, SECURITY,
    DATA_SCIENCE, UX_UI, DESIGNER, PROJECT_MANAGER, OTHER,
}
